### ISSUE TITLE
Unable to build the SDK

### ISSUE THREAD

**Issue by zyga** [NexaAI/nexa-sdk#1066]
### Pre-checks

- [x] I searched existing issues
- [x] I’m using the latest NexaSDK release

### What happened?

```text
Attempting to build the runner with go 1.26.2 in `nexa-sdk/runner` I get:


$ make
go build -ldflags "-s -w" -o build/nexa ./cmd/nexa-launcher
go build -tags="sonic avx" -ldflags "-X 'main.Version=' -s -w" -o build/nexa-cli ./cmd/nexa-cli
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.14.2/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.14.2/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [Makefile:38: build] Error 1
```

### Steps to reproduce

```markdown
1. Clone the repo
2. run `make download` to fetch the binary blobs
3. run `make`
```

### Logs & stack traces

```text
zyga@thinkpad-t14-1:~/Dokumenty/nexa-sdk/runner$ LANG=C make 
go build -ldflags "-s -w" -o build/nexa ./cmd/nexa-launcher
go build -tags="sonic avx" -ldflags "-X 'main.Version=' -s -w" -o build/nexa-cli ./cmd/nexa-cli
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.14.2/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.14.2/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [Makefile:38: build] Error 1
```

### Model(s) and quantization

```text

```

### NexaSDK version

N/A (git 1915274c7ef6687fe68781973aada7d263783463)

### Install method

source

### OS and version

Ubuntu 26.04

### Hardware / accelerator

Snapdragon X Elite

### Additional context

```markdown

```

**Comment by mengshengwu** [comment]
This was against the old `runner/` + Makefile layout, which is gone — GenieX now builds with Bazel. The error itself is `bytedance/sonic` v1.14.2 not supporting Go 1.26 (it broke on the map-iterator change); we've since bumped to sonic v1.15.1, which builds fine on 1.26. So a fresh clone won't hit this. Closing as resolved — reopen if you still see it on current `main`.
